<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for
     more information on what is customizable.
     By default, only the Clean and Build commands use this build script.
     Commands such as Run, Debug, and Test only use this build script if
     the Compile on Save feature is turned off for the project.
     You can turn off the Compile on Save (or Deploy on Save) setting
     for the application in the project's Project Properties dialog box.
     NOTE: nbproject/build-impl.xml is generated automatically by NetBeans
     the first time this project is opened or built. If it is missing,
     that is expected and normal. -->
<project name="NominaGuate" default="default" basedir=".">
    <description>Builds, tests, and runs the project NominaGuate.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
